---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-api-db
  namespace: default
  labels:
    app: golang-api
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-api
      tier: db
  template:
    metadata:
      labels:
        app: golang-api
        tier: db
    spec:
      containers:
        - name: golang-api
          image: registry-intl.ap-southeast-3.aliyuncs.com/wicky-dev/mysql:8.1.0
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "my-secret-pw"
          - name: MYSQL_DATABASE
            value: "api"
          - name: MYSQL_USER
            value: "api"
          - name: MYSQL_PASSWORD
            value: "password123"
          ports:
            - containerPort: 3306
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: golang-api-db-svc
  namespace: default
  labels:
    app: golang-api
    tier: db
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: golang-api
    tier: db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-api
  namespace: default
  labels:
    app: golang-api
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-api
      tier: app
  template:
    metadata:
      labels:
        app: golang-api
        tier: app
    spec:
      containers:
        - name: golang-api
          image: registry-intl.ap-southeast-3.aliyuncs.com/wicky-dev/golang-api:1.0.0
          env:
          - name: DB_HOST
            value: "golang-api-db-svc"
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: "api"
          - name: DB_USER
            value: "api"
          - name: DB_PASSWORD
            value: "password123"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: golang-api-svc
  namespace: default
  labels:
    app: golang-api
    tier: app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: golang-api
    tier: app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-api-ingress
  namespace: default
  labels:
    app: golang-api
    tier: app
spec:
  rules:
  - host: golang-api.gentingmalaysia.com
    http:
      paths:
      - path: /
        backend:
          service: 
            name: golang-api-svc
            port:
              number: 8080
        pathType: ImplementationSpecific
        
